# ==============================================================================
# Ansible Inventory: Spring Petclinic Deployment (localhost)
# Usage: ansible-playbook -i inventory.ini deploy.yml
# ==============================================================================

[app_servers]
petclinic-host ansible_host=127.0.0.1 ansible_connection=local ansible_user=uday 
[app_servers:vars]
ansible_python_interpreter=/usr/bin/python3
